import { dom, library } from '@fortawesome/fontawesome-svg-core';

import {
  faArrowDownToLine,
  faArrowLeft,
  faArrowsToLine,
  faArrowUpFromLine,
  faArrowsLeftRightToLine,
  faBalanceScale,
  faBallotCheck,
  faBell,
  faBriefcase,
  faChartBar,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCog,
  faColumns3,
  faCommentAltExclamation,
  faEdit,
  faEllipsisH,
  faExclamationCircle,
  faExclamationTriangle,
  faExternalLink,
  faEye,
  faFileAlt,
  faFileMedicalAlt,
  faFilePowerpoint,
  faFilter,
  faHandPaper,
  faHighlighter,
  faInbox,
  faInfoCircle,
  faListOl,
  faListUl,
  faLongArrowAltDown,
  faLongArrowAltLeft,
  faLongArrowAltUp,
  faMagnifyingGlass,
  faMinus,
  faPaperclip,
  faPaperPlane,
  faPen,
  faPipe,
  faPlus,
  faQuestionCircle,
  faSave,
  faSquare as faSquareLight,
  faTable,
  faTextSize,
  faTimes,
  faTimesCircle,
  faTrashAlt,
  faUndo,
  faUserCircle,
  faUserLock,
  faUserUnlock,
  faWindowMaximize,
} from '@fortawesome/pro-light-svg-icons';

import {
  // Text editor
  faBold,
  faHorizontalRule,
  faImage,
  faIndent,
  faItalic,
  faLink,
  faOutdent,
  faPalette,
  faStrikethrough,
  faUnderline,
} from '@fortawesome/pro-regular-svg-icons';

// Button and checkbox
import { faCaretDown, faSquare, faSquareCheck, faSort, faSortDown, faSortUp } from '@fortawesome/pro-solid-svg-icons';

const loadIcons = (): void => {
  library.add(
    faArrowDownToLine,
    faArrowLeft,
    faArrowsLeftRightToLine,
    faArrowsToLine,
    faArrowUpFromLine,
    faBalanceScale,
    faBallotCheck,
    faBell,
    faBriefcase,
    faChartBar,
    faCheck,
    faChevronDown,
    faChevronLeft,
    faChevronRight,
    faCog,
    faColumns3,
    faCommentAltExclamation,
    faEdit,
    faEllipsisH,
    faExclamationCircle,
    faExclamationTriangle,
    faExternalLink,
    faEye,
    faFileAlt,
    faFileMedicalAlt,
    faFilePowerpoint,
    faFilter,
    faHandPaper,
    faInbox,
    faInfoCircle,
    faLongArrowAltDown,
    faLongArrowAltLeft,
    faLongArrowAltUp,
    faMagnifyingGlass,
    faMinus,
    faPaperclip,
    faPaperPlane,
    faPen,
    faPipe,
    faPlus,
    faQuestionCircle,
    faSave,
    faSort,
    faSortDown,
    faSortUp,
    faSquareLight,
    faTimes,
    faTimesCircle,
    faTrashAlt,
    faUndo,
    faUserCircle,
    faUserLock,
    faUserUnlock,
    faWindowMaximize,

    // text editor
    faBold,
    faHighlighter,
    faHorizontalRule,
    faImage,
    faIndent,
    faItalic,
    faLink,
    faListOl,
    faListUl,
    faOutdent,
    faPalette,
    faStrikethrough,
    faTable,
    faTextSize,
    faUnderline,

    // button
    faCaretDown,
    faSquare,
    faSquareCheck,
  );

  dom.watch();
};

export default loadIcons;
